-- generated by github copilot

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package rom_pkg is
  -- example enum; replace with your actual members
  type state_t is (S0, S1, S2, S3, S4, S5, S6, S7);
end package rom_pkg;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.rom_pkg.all;

entity rom64_enum is
  port (
    clk  : in  std_logic;
    addr : in  std_logic_vector(5 downto 0);
    dout : out state_t
  );
end entity rom64_enum;

architecture rtl of rom64_enum is
  type rom_t is array (0 to 63) of state_t;

  -- apply Xilinx attribute to the signal to encourage LUTRAM (distributed)
  attribute ram_style : string;
  attribute ram_style of rom_mem : signal is "distributed";

  -- initialize ROM with enum literals (clean and readable)
  signal rom_mem : rom_t := (
    0  => S1,
    1  => S2,
    2  => S3,
    3  => S4,
    -- ... fill entries 0..63 with enum values ...
    others => S0
  );

  signal dout_reg : state_t;
begin
  -- synchronous read (1-cycle latency)
  process(clk)
  begin
    if rising_edge(clk) then
      dout_reg <= rom_mem(to_integer(unsigned(addr)));
    end if;
  end process;

  dout <= dout_reg;
end architecture rtl;